Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "kali" do |kali|
    kali.vm.box = "kali-redscope"
    kali.vm.hostname = "redscope-kali"
    kali.vm.network "private_network", ip: "10.77.0.10"
    kali.vm.provider "virtualbox" do |vb|
      vb.name = "RedScope-Kali"
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  config.vm.define "metasploitable2" do |target|
    target.vm.box = "metasploitable2-redscope"
    target.vm.hostname = "redscope-metasploitable2"
    target.vm.network "private_network", ip: "10.77.0.3"
    target.vm.provider "virtualbox" do |vb|
      vb.name = "RedScope-Metasploitable2"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
